### PR TITLE
Make moodle-dl use asyncio

### PR DESCRIPTION
**Pull request by C0D3D3V**
All Moodle API calls and all download functions are made asynchronous (not all file system accesses)

Still needs testing

### CODE REVIEW

**Comment by daniarla** [comment]
I just initialized the course with a new token and configuration so I don't mess up my main download folder and after the first successful configuration and init I got this error:
```
The following error occurred during execution:
stat: path should be string, bytes, os.PathLike or integer, not NoneType
11:58:47 Exception: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by C0D3D3V** [comment]
sorry @daniarla 

xD this PR is still in a unstable state. I should put it in draft mode. I only opended the PR because now all async functions are implemented. 

I will ask you again for testing as soon as I think its ready.

**Comment by daniarla** [comment]
No problem, I saw my issue mentioned and I thought that it was finished! My bad :stuck_out_tongue_winking_eye:
I skim through the commits and It looks promising! Great job!!!

**Comment by C0D3D3V** [comment]
But still interesting error you got there :D But not very helpful. Later when I ask for testing, please run in verbose mode, maybe that will give me more information what is wrong.  And use the new option --log-to-file.

**Comment by C0D3D3V** [comment]
I think this is now ready for testing. At least my tests were successful. I will test a little bit more with some edge cases and hope you also can test it before I merge and release it. @daniarla @AlphaJack @marcoscale98

**Comment by daniarla** [comment]
I got the same bug as before. Should I open an issue? Can i report you all the details privately?

The problem is that for some reason Moodle-DL doesn't save the cookies even though I specify to do so. When trying to run it doesn't find the cookies file and crash. (There is no cookies.txt in my directory)

```
File "/home/me/Documents/Gits/Moodle-DL/moodle_dl/moodle/moodle_service.py", line 108, in fetch_state
    cookie_handler.check_and_fetch_cookies(privatetoken, user_id)

File "/home/me/Documents/Gits/Moodle-DL/moodle_dl/moodle/cookie_handler.py", line 56, in check_and_fetch_cookies
    if os.path.exists(self.cookies_path):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by C0D3D3V** [comment]
Ah that helped already, I think (at least know I know where the error happens). I will make a fix later today and will ask for a second try. 
Thank you.

**Comment by C0D3D3V** [comment]
This should also fix #181  but I have to test it.

**Comment by C0D3D3V** [comment]
@daniarla I guess the last commit fixed the error. For me it works

**Comment by daniarla** [comment]
Works for me too! Now it remains to see if the cookie regenerates ok.

**Comment by daniarla** [comment]
@C0D3D3V  I just tested and if the cookie is not valid it re-generates one perfectly!!

**Comment by C0D3D3V** [comment]
> I'll wait for the merge and then close #168 smile

Do not worry, I close the related issues as soon as I have done the release.

**Pull request merged**
